server:
  port: 31200
spring:
  application:
    name: servicemanager-course
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xc_course
    username: root
    password: a75767626
  jpa:
    database: MySQL
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL57Dialect  #不加这句则默认为myisam引
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    #        dialect: org.hibernate.dialect.MySQL57Dialect #不加这句则默认为myisam引
    hibernate:
      ddl-auto: update
  #mybatis的相关配置
  mybatis:
    #mapper配置文件
    mapper-locations: classpath*:com/wenbronk/framework/repository/course/*.xml
    type-aliases-package: com.xuecheng.framework.domain.course
    #开启驼峰命名
    configuration:
      map-underscore-to-camel-case: true
pagehelper:
  helper‐dialect: mysql