server:
  port: 8081
spring:
  application:
    name: shiro-springboot #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: a75767626
  jpa:
    database: MySQL
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL57Dialect  #不加这句则默认为myisam引
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.MySQL57Dialect #不加这句则默认为myisam引
    hibernate:
      ddl-auto: update

  redis:
    host: 127.0.0.1
    port: 6379