server:
  port: 31001
#  servlet:
#    context-path: /api
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://xczx:1234@localhost:27017
      database: xc_cms
      authentication-database: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/xczx_jpa
#    driver-class-name: net.sf.log4jdbc.DriverSpy
#    url: jdbc:log4jdbc:mysql://localhost:13306/xczx_jpa
    username: root
    password: a75767626
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create